# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbd35e9e0a48585c3c9f212cf2d1545024c629886a144976c73e82d220530e5b326288f002586ed432b7579de2a432a7f031a3604865ace32701fd4cc3cdfb86

test:
  secret_key_base: 43eee79d473c64f4a04c6c852f2a7277f21d28a62e3598bd958a45a784c33695095d83686eeab555c2676701bf22097d065ace1bff6c2e7b27f58d00ae42c11e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
